Web 1090 adapt dependencies
xing/rlsr pull request #71
Opened 2021-07-19 16:51 UTC by santiph

2021-07-21 06:05 UTC, matthias-reis requested changes

2021-07-21 10:10 UTC, santiph commented on new/analyse/adapt-dependencies/adapt-dependencies.ts
> +    const currentPackage = releasablePackages[packageName];
Good catch. I'll change it

2021-07-21 10:32 UTC, santiph commented on new/analyse/adapt-dependencies/get-releasable-packages.ts
> +    const currentPackage = packages![packageName];
Awesome! I was not aware of this! :D
I had to change the tsconfig's `target` option from `es2017` to `es2019`, tho

2021-07-21 11:08 UTC, santiph commented on new/analyse/adapt-dependencies/adapt-dependencies.ts
> +      // @TODO: repeat for dependingPackage's "dependsOn" entry?
I'll change this, too

2021-07-26 08:59 UTC, matthias-reis commented on new/analyse/adapt-dependencies/get-releasable-packages.ts
> +    const currentPackage = packages![packageName];
Oh damn. Didn't know. But it should™ be fine. Depends on the server side node version.

2021-07-26 09:06 UTC, matthias-reis commented on new/analyse/adapt-dependencies/spec/adapt-dependencies.spec.ts
> +      'throws exception if no package can be found on "dependsOn" collection'
Why that? If the package doesn't depend on any other, this is rather a good thing and should not stop the process?!?

2021-07-26 09:06 UTC, matthias-reis commented on new/analyse/adapt-dependencies/spec/adapt-dependencies.spec.ts
> +    it.todo('throws exception if upper version limit cannot be determined');
Upper limit is always calculated from the current version. So this will not be needed.

2021-07-26 11:29 UTC, matthias-reis approved these changes

2021-07-26 11:29 UTC, matthias-reis commented
Merging this here as discussed...

2021-07-26 11:29 UTC, merged