chore: persist release changes in case push failed
xing/rlsr pull request #91
Opened 2021-08-02 13:19 UTC by Irysomka

2021-08-02 14:10 UTC, matthias-reis commented on src/persist/push-changes.ts
>      error('Error pushing changes');
Can you add the created branch to the error message?

2021-08-02 14:10 UTC, matthias-reis requested changes
/

2021-08-02 15:06 UTC, santiph commented on src/persist/push-changes.ts
> +    await git.checkoutBranch(backupBranchName, branch);
unit tests please 👀

2021-08-03 08:31 UTC, matthias-reis approved these changes

2021-08-03 08:31 UTC, merged